spring:
  application:
    name: storeMe
  flyway:
    enabled: true
    baseline-on-migrate: true
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  profile:
    active: dev
jwt:
  secret: mysecretkey
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000
