-- DROP previous version
ALTER TABLE folders DROP COLUMN IF EXISTS path;
ALTER TABLE files DROP COLUMN IF EXISTS path;

-- Add new columns
-- folders new columns
ALTER TABLE folders ADD COLUMN IF NOT EXISTS ancestor BIGINT[];
ALTER TABLE folders ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE folders ADD COLUMN IF NOT EXISTS is_locked BOOLEAN DEFAULT FALSE;
ALTER TABLE folders ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN DEFAULT FALSE;
ALTER TABLE folders ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'NORMAL';

-- files new columns
ALTER TABLE files ADD COLUMN IF NOT EXISTS ancestor BIGINT[];
ALTER TABLE files ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE files ADD COLUMN IF NOT EXISTS blob_key VARCHAR(255) NOT NULL;

-- add version
ALTER TABLE folders ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE files ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE verifications ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE storage_plans ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE user_plans ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
