CREATE TABLE IF NOT EXISTS verifications (
    id BIGSERIAL PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    expirated_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
